### ISSUE TITLE
Fails on native functions, like Number or String

### ISSUE THREAD

**Issue by TheJaredWilcurt** [yahoo/serialize-javascript#179]
```js
const serializeJavaScript = require('serialize-javascript');

const input = {
  type: Number
};

const output = serializeJavaScript(input);

console.log(output);
```

**Expected:**

`{"type":Number}`

**Actual:**

```
Uncaught TypeError: Serializing native function: Number
    at serializeFunc (/node_modules/serialize-javascript/index.js:146:17)
    at /node_modules/serialize-javascript/index.js:266:16
    at String.replace (<anonymous>)
    at serialize (/node_modules/serialize-javascript/index.js:220:16)
```

**Comment by TheJaredWilcurt** [comment]
```js
const x = Number;
console.log(x === Number); // true
```
Since you can check for native constructors, a conditional formatter could be added:
```js
/**
 * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects
 * Note: Not all global objects listed there can be combined when an empty string to
 * produce a native function string, needed in the following condition.
 */
const nativeConstructors = [
  AggregateError,
  Array,
  ArrayBuffer,
  BigInt,
  BigInt64Array,
  BigUint64Array,
  Boolean,
  DataView,
  Date,
  Error,
  EvalError,
  FinalizationRegistry,
  Float32Array,
  Float64Array,
  Function,
  Int8Array,
  Int16Array,
  Int32Array,
  Intl.Collator,
  Intl.DateTimeFormat,
  Intl.DisplayNames,
  Intl.ListFormat,
  Intl.Locale,
  Intl.NumberFormat,
  Intl.PluralRules,
  Intl.RelativeTimeFormat,
  Intl.Segmenter,
  Iterator,
  Map,
  Number,
  Object,
  Promise,
  Proxy,
  RangeError,
  ReferenceError,
  RegExp,
  Set,
  SharedArrayBuffer,
  String,
  Symbol,
  SyntaxError,
  TypeError,
  Uint8Array,
  Uint8ClampedArray,
  Uint16Array,
  Uint32Array,
  URIError,
  WeakMap,
  WeakRef,
  WeakSet
];

if (nativeConstructors.includes(value)) {
  // Number => 'function Number() { [native code] }' => 'Number'
  return (value + '').split(' ')[1].split('(')[0];
}
```

**Comment by TheJaredWilcurt** [comment]
If you prefer a harder to read, but marginally faster to execute regex approach for the last conditional:

```js
if (nativeConstructors.includes(value)) {
  // Number => 'function Number() { [native code] }'
  const functionString = '' + value;
  const hasName = functionString.match(/function\s(\w+)\(\)/);
  if (hasName) {
    // 'Number'
    const name = hasName[1];
    return name;
  }
}
```

**Comment by TheJaredWilcurt** [comment]
I'll leave this to @redonkulus to figure out the best way to implement this solution. Since this repo relies on Node specific stuff (Buffer), and my use case needs to work in a browser I just wrote [my own serializer](https://github.com/TheJaredWilcurt/vue-doxen/blob/v0.1.0/lib/helpers/serializeJavaScript.js#L46) for my project.

**Comment by zhangyx1998** [comment]
I recently created a package _[living-object](https://www.npmjs.com/package/living-object)_ that covers this case. Perhaps you'll find it useful 😀

Here is a playground if you'd like to try it out: [stakblitz/living-object](https://stackblitz.com/edit/living-object?file=demo.js)
